version: '3'
services:
  flask-api:
    image: python:3.11-slim
    container_name: flask_api
    volumes:
      - /home/ian/mainapi:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - 6464:5000
    restart: unless-stopped
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

